import type {
  Task,
  TaskResponse,
  TasksResponse,
  TaskUser,
} from '@/models/Task';
import type { User } from '@/models/User';
import { logMessage } from '@/utils/logger';
import type { Request, Response } from 'express';
import { users } from './UsersService';

const userIds: Record<'alex' | 'sarah' | 'mike' | 'emma', User['id']> = {
  alex: 1,
  sarah: 2,
  mike: 3,
  emma: 4,
};

const userById = (id: User['id']): TaskUser => {
  const user = users.find((u) => u.id === id);
  if (!user) {
    throw new Error(`User with id ${id} not found`);
  }
  const { name, email, avatar, role } = user;
  return { id, name, email, avatar, role };
};

const mapUsers = (...ids: User['id'][]): TaskUser[] => ids.map(userById);

const tasks: Task[] = [
  {
    id: 1,
    title: 'Initial Planning & Requirements Gathering',
    description:
      'Meet with stakeholders to gather requirements and create project plan',
    status: 'completed',
    priority: 'high',
    assignedTo: mapUsers(userIds.alex, userIds.sarah),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-03T00:00:00.000Z',
    updatedAt: '2025-01-07T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: '2025-01-03T00:00:00.000Z',
    endDate: '2025-01-07T00:00:00.000Z',
    dueDate: '2025-01-09T00:00:00.000Z',
    tags: ['planning', 'requirements'],
    projectId: 1,
  },
  {
    id: 2,
    title: 'UI/UX Design & Mockups',
    description: 'Create wireframes, user flows, and high-fidelity mockups',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: mapUsers(userIds.sarah, userIds.emma),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-09T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: '2025-01-10T00:00:00.000Z',
    endDate: null,
    dueDate: '2025-01-24T00:00:00.000Z',
    tags: ['design', 'ui/ux', 'mockups'],
    projectId: null,
  },
  {
    id: 3,
    title: 'Frontend Development - Homepage',
    description: 'Build responsive homepage with modern design patterns',
    status: 'todo',
    priority: 'low',
    assignedTo: mapUsers(userIds.alex, userIds.sarah),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-14T00:00:00.000Z',
    updatedAt: '2025-01-14T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-01-31T00:00:00.000Z',
    tags: ['frontend', 'react', 'responsive'],
    projectId: 1,
  },
  {
    id: 4,
    title: 'Frontend Development - Internal Pages',
    description: 'Develop about, contact, and services pages',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.alex, userIds.sarah),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-15T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-07T00:00:00.000Z',
    tags: ['frontend', 'pages'],
    projectId: 1,
  },
  {
    id: 5,
    title: 'Content Management Integration',
    description: 'Integrate CMS for easy content updates',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.emma),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-16T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-11T00:00:00.000Z',
    tags: ['cms', 'integration'],
    projectId: 1,
  },
  {
    id: 6,
    title: 'Mobile App Architecture Design',
    description: 'Design app architecture and technology stack',
    status: 'completed',
    priority: 'high',
    assignedTo: mapUsers(userIds.mike),
    createdBy: userById(userIds.mike),
    createdAt: '2025-01-07T00:00:00.000Z',
    updatedAt: '2025-01-09T00:00:00.000Z',
    updatedBy: userById(userIds.mike),
    startDate: '2025-01-07T00:00:00.000Z',
    endDate: '2025-01-10T00:00:00.000Z',
    dueDate: '2025-01-11T00:00:00.000Z',
    tags: ['architecture', 'planning'],
    projectId: 2,
  },
  {
    id: 7,
    title: 'User Authentication System',
    description: 'Implement login, registration, and password reset',
    status: 'in-progress',
    priority: 'low',
    assignedTo: mapUsers(userIds.mike),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-12T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: '2025-01-13T00:00:00.000Z',
    endDate: null,
    dueDate: '2025-01-22T00:00:00.000Z',
    tags: ['authentication', 'security', 'mobile'],
    projectId: 2,
  },
  {
    id: 8,
    title: 'Core Features Implementation',
    description: 'Build main app features and user flows',
    status: 'todo',
    priority: 'high',
    assignedTo: mapUsers(userIds.sarah, userIds.mike),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-14T00:00:00.000Z',
    updatedAt: '2025-01-14T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-01-29T00:00:00.000Z',
    tags: ['features', 'development'],
    projectId: 2,
  },
  {
    id: 9,
    title: 'Push Notifications Setup',
    description: 'Configure push notifications for user engagement',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.sarah),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-15T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-04T00:00:00.000Z',
    tags: ['notifications', 'engagement'],
    projectId: 2,
  },
  {
    id: 10,
    title: 'Payment Gateway Research',
    description: 'Evaluate and select payment processing solutions',
    status: 'completed',
    priority: 'high',
    assignedTo: mapUsers(userIds.sarah, userIds.mike),
    createdBy: userById(userIds.sarah),
    createdAt: '2025-01-09T00:00:00.000Z',
    updatedAt: '2025-01-11T00:00:00.000Z',
    updatedBy: userById(userIds.sarah),
    startDate: '2025-01-09T00:00:00.000Z',
    endDate: '2025-01-12T00:00:00.000Z',
    dueDate: '2025-01-13T00:00:00.000Z',
    tags: ['research', 'payments'],
    projectId: 3,
  },
  {
    id: 11,
    title: 'Stripe API Integration',
    description: 'Integrate Stripe for payment processing',
    status: 'in-progress',
    priority: 'low',
    assignedTo: mapUsers(userIds.mike),
    createdBy: userById(userIds.sarah),
    createdAt: '2025-01-13T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
    updatedBy: userById(userIds.sarah),
    startDate: '2025-01-14T00:00:00.000Z',
    endDate: null,
    dueDate: '2025-01-20T00:00:00.000Z',
    tags: ['stripe', 'api', 'payments'],
    projectId: 3,
  },
  {
    id: 12,
    title: 'Shipping API Integration',
    description: 'Integrate UPS and FedEx shipping APIs',
    status: 'todo',
    priority: 'low',
    assignedTo: mapUsers(userIds.sarah),
    createdBy: userById(userIds.sarah),
    createdAt: '2025-01-15T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
    updatedBy: userById(userIds.sarah),
    startDate: null,
    endDate: null,
    dueDate: '2025-01-25T00:00:00.000Z',
    tags: ['shipping', 'api', 'logistics'],
    projectId: 3,
  },
  {
    id: 13,
    title: 'Payment Testing & Validation',
    description: 'Test payment flows and ensure PCI compliance',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.mike),
    createdBy: userById(userIds.sarah),
    createdAt: '2025-01-16T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
    updatedBy: userById(userIds.sarah),
    startDate: null,
    endDate: null,
    dueDate: '2025-01-27T00:00:00.000Z',
    tags: ['testing', 'security', 'validation'],
    projectId: 3,
  },
  {
    id: 14,
    title: 'Error Handling & Monitoring',
    description: 'Implement error handling and monitoring for API calls',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.sarah),
    createdBy: userById(userIds.sarah),
    createdAt: '2025-01-17T00:00:00.000Z',
    updatedAt: '2025-01-17T00:00:00.000Z',
    updatedBy: userById(userIds.sarah),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-01T00:00:00.000Z',
    tags: ['monitoring', 'error-handling'],
    projectId: 3,
  },
  {
    id: 15,
    title: 'Responsive Design Implementation',
    description:
      'Ensure all pages work perfectly on mobile, tablet, and desktop',
    status: 'completed',
    priority: 'high',
    assignedTo: mapUsers(userIds.alex, userIds.sarah),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-05T00:00:00.000Z',
    updatedAt: '2025-01-09T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: '2025-01-06T00:00:00.000Z',
    endDate: '2025-01-09T00:00:00.000Z',
    dueDate: '2025-01-10T00:00:00.000Z',
    tags: ['responsive', 'css', 'testing'],
    projectId: 1,
  },
  {
    id: 16,
    title: 'SEO Implementation',
    description: 'Implement meta tags, structured data, and SEO optimization',
    status: 'in-progress',
    priority: 'high',
    assignedTo: mapUsers(userIds.alex),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-11T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: '2025-01-12T00:00:00.000Z',
    endDate: null,
    dueDate: '2025-01-20T00:00:00.000Z',
    tags: ['seo', 'meta-tags', 'optimization'],
    projectId: 1,
  },
  {
    id: 17,
    title: 'Performance Optimization',
    description: 'Optimize images, minify assets, and implement lazy loading',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.sarah),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-13T00:00:00.000Z',
    updatedAt: '2025-01-13T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-01-30T00:00:00.000Z',
    tags: ['performance', 'optimization', 'images'],
    projectId: 1,
  },
  {
    id: 18,
    title: 'Accessibility Testing',
    description:
      'Ensure WCAG 2.1 AA compliance and screen reader compatibility',
    status: 'todo',
    priority: 'high',
    assignedTo: mapUsers(userIds.alex, userIds.emma),
    createdBy: userById(userIds.emma),
    createdAt: '2025-01-14T00:00:00.000Z',
    updatedAt: '2025-01-14T00:00:00.000Z',
    updatedBy: userById(userIds.emma),
    startDate: null,
    endDate: null,
    dueDate: '2025-01-27T00:00:00.000Z',
    tags: ['accessibility', 'wcag', 'testing'],
    projectId: 1,
  },
  {
    id: 19,
    title: 'Cross-browser Testing',
    description: 'Test and fix issues on Chrome, Firefox, Safari, and Edge',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.sarah, userIds.mike),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-15T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-14T00:00:00.000Z',
    tags: ['testing', 'browsers', 'compatibility'],
    projectId: 1,
  },
  {
    id: 20,
    title: 'Analytics Integration',
    description: 'Integrate Google Analytics and custom event tracking',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.alex),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-16T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-12T00:00:00.000Z',
    tags: ['analytics', 'tracking', 'metrics'],
    projectId: 1,
  },
  {
    id: 21,
    title: 'Security Audit & Hardening',
    description: 'Conduct security audit and implement security headers',
    status: 'todo',
    priority: 'high',
    assignedTo: mapUsers(userIds.alex, userIds.mike),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-16T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-16T00:00:00.000Z',
    tags: ['security', 'audit', 'headers'],
    projectId: 1,
  },
  {
    id: 22,
    title: 'Deployment Pipeline Setup',
    description:
      'Configure CI/CD pipeline with automated testing and deployment',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.sarah, userIds.mike),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-17T00:00:00.000Z',
    updatedAt: '2025-01-17T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-21T00:00:00.000Z',
    tags: ['deployment', 'ci/cd', 'automation'],
    projectId: 1,
  },
  {
    id: 23,
    title: 'Standalone Task for Testing',
    description: 'This is a standalone task created for testing purposes',
    status: 'todo',
    priority: 'medium',
    assignedTo: mapUsers(userIds.alex),
    createdBy: userById(userIds.alex),
    createdAt: '2025-01-17T00:00:00.000Z',
    updatedAt: '2025-01-17T00:00:00.000Z',
    updatedBy: userById(userIds.alex),
    startDate: null,
    endDate: null,
    dueDate: '2025-02-21T00:00:00.000Z',
    tags: ['test'],
    projectId: null,
  },
];

export class TasksService {
  async getAll(req: Request, _res: Response): Promise<TasksResponse> {
    logMessage('Fetching all tasks', 'info');
    const status = req.query.status as string | undefined;
    return {
      status: 200,
      data: tasks.filter((task) => !status || task.status === status) as Task[],
    };
  }

  async getOne(req: Request, _res: Response): Promise<TaskResponse> {
    logMessage(`Fetching task with id: ${req.params.id}`, 'info');
    if (!req.params.id) {
      return {
        status: 400,
        data: null,
      };
    }
    const id = Number(req.params.id);
    const task = tasks.find((t) => t.id === id) || null;
    return {
      status: 200,
      data: task,
    };
  }

  async update(req: Request, _res: Response): Promise<TaskResponse> {
    logMessage(`Updating task with id: ${req.params.id}`, 'info');
    if (!req.params.id) {
      return {
        status: 400,
        data: null,
      };
    }
    const id = Number(req.params.id);
    const taskIndex = tasks.findIndex((t) => t.id === id);
    if (taskIndex === -1) {
      return {
        status: 404,
        data: null,
      };
    }
    const updatedTaskData: Partial<Task> = req.body;
    const existingTask = tasks[taskIndex];
    const updatedTask: Task = {
      ...existingTask,
      ...updatedTaskData,
      id: existingTask.id, // Ensure ID is not changed
      updatedAt: new Date().toISOString(),
    };
    tasks[taskIndex] = updatedTask;
    return {
      status: 200,
      data: updatedTask,
    };
  }
}
